#!/bin/sh

errno=0
/bin/mount -t devtmpfs devtmpfs /dev

if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi

/bin/mount -t proc proc /proc

rootdev=$(/bin/cat /proc/cmdline | cut -d ' ' -f3 | cut -d '=' -f2)

/sbin/fsck ${rootdev}
errno=$?

if [ $errno -eq 8 ]; then
	/bin/umount ${rootdev}
	/sbin/fsck ${rootdev}
fi

if [ $errno -ne 0 && $errno != 8 ]; then
	/bin/sh
fi

/bin/mount ${rootdev} /mnt

exec /mnt/sbin/switch_root /mnt /sbin/init
