######################################################
#
# sunshine
#
######################################################

SUNSHINE_VERSION = c435d0fe56aa661fab6c57503787f5bd86f76032
SUNSHINE_SITE_METHOD = git
SUNSHINE_GIT_SUBMODULES = YES
SUNSHINE_SITE = https://github.com/baidxi/Sunshine
SUNSHINE_LICENSE = GPL-3.0
SUNSHINE_LICENSE_FILES = LICENSE.txt
SUNSHINE_DEPENDENCIES = boost wayland wayland-protocols libcurl libminiupnpc ffmpeg

SUNSHINE_CONF_OPTS += \
	-DSUNSHINE_ENABLE_DRM:BOOL=ON	\
	-DSUNSHINE_ENABLE_WAYLAND:BOOL=ON \
	-DSUNSHINE_ENABLE_X11:BOOL=ON

ifeq ($(BR2_PACKAGE_SUNSHINE_USE_STATIC_BOOST),y)
SUNSHINE_CONF_OPTS += -DBOOST_USE_STATIC:BOOL=ON
else
SUNSHINE_CONF_OPTS += -DBOOST_USE_STATIC:BOOL=OFF
endif

ifeq ($(BR2_PACKAGE_SUNSHINE_BUILD_APPIMAGE),y)
SUNSHINE_CONF_OPTS += -DSUNSHINE_BUILD_APPIMAGE:BOOL=ON
else
SUNSHINE_CONF_OPTS += -DSUNSHINE_BUILD_APPIMAGE:BOOL=OFF
endif

ifeq ($(BR2_PACKAGE_SUNSHINE_BUILD_FLATPAK),y)
SUNSHINE_CONF_OPTS += -DSUNSHINE_BUILD_FLATPAK:BOOL=ON
else
SUNSHINE_CONF_OPTS += -DSUNSHINE_BUILD_FLATPAK:BOOL=OFF
endif

ifeq ($(BR2_PACKAGE_SUNSHINE_CONFIGURE_PKGBUILD),y)
SUNSHINE_CONF_OPTS += -DSUNSHINE_CONFIGURE_PKGBUILD:BOOL=ON
else
SUNSHINE_CONF_OPTS += -DSUNSHINE_CONFIGURE_PKGBUILD:BOOL=OFF
endif

ifeq ($(BR2_PACKAGE_SUNSHINE_ENABLE_CUDA),y)
SUNSHINE_CONF_OPTS += -DSUNSHINE_ENABLE_CUDA:BOOL=ON
else
SUNSHINE_CONF_OPTS += -DSUNSHINE_ENABLE_CUDA:BOOL=OFF
endif

ifeq ($(BR2_PACKAGE_SUNSHINE_ENABLE_DRM),y)
SUNSHINE_CONF_OPTS += -DSUNSHINE_ENABLE_DRM:BOOL=ON
else
SUNSHINE_CONF_OPTS += -DSUNSHINE_ENABLE_DRM:BOOL=OFF
endif

ifeq ($(BR2_PACKAGE_SUNSHINE_ENABLE_VAAPI),y)
SUNSHINE_CONF_OPTS += -DSUNSHINE_ENABLE_VAAPI:BOOL=ON
else
SUNSHINE_CONF_OPTS += -DSUNSHINE_ENABLE_VAAPI:BOOL=OFF
endif

ifeq ($(BR2_PACKAGE_SUNSHINE_ENABLE_WAYLAND),y)
SUNSHINE_CONF_OPTS += -DSUNSHINE_ENABLE_WAYLAND:BOOL=ON
else
SUNSHINE_CONF_OPTS += -DSUNSHINE_ENABLE_WAYLAND:BOOL=OFF
endif

ifeq ($(BR2_PACKAGE_SUNSHINE_ENABLE_X11),y)
SUNSHINE_CONF_OPTS += -DSUNSHINE_ENABLE_X11:BOOL=ON
else
SUNSHINE_CONF_OPTS += -DSUNSHINE_ENABLE_X11:BOOL=OFF
endif

$(eval $(cmake-package))