#!/bin/sh

if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi

mount -t proc proc /proc
mount -t sysfs sysfs /sys

rootdev=$(mount | awk '$3 == "/" {print $1}')

umount ${rootdev}

fsck ${rootdev} 2>/dev/null

/bin/mount ${rootdev} /mnt

exec /mnt/sbin/switch_root /mnt /sbin/init
