#!/bin/sh

/bin/mount -t devtmpfs devtmpfs /dev

if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi

/bin/mount -t proc proc /proc

rootdev=$(/bin/cat /proc/cmdline | cut -d ' ' -f2 | cut -d '=' -f2)

/sbin/fsck ${rootdev}

if [ $? -ne 0 ]; then
	/bin/sh
fi

/bin/mkdir /rootfs

/bin/mount ${rootdev} /rootfs

exec /rootfs/sbin/switch_root /rootfs /linuxrc
